app = "cloudflare-masque"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "1080"

[[services]]
  protocol = "tcp"
  internal_port = 1080
  
  [[services.ports]]
    port = 1080
    handlers = []
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
